languageCode = "en"
languageName = "English"
displayName = "EN"
isoCode = "en"
weight = 1
rtl = false

title = "lelouvincx's blog"
# logo = "img/avatar.png"
description = "My awesome website"
# copyright = "Copy, _right?_ :thinking_face:"

dateFormat = "2006-01-02"

[author]
  name = "lelouvincx"
  image = "img/avatar.png"
  # headline = "I'm writing about data science, dev life, productivity, and linux. Let's discover!"
  headline = "Mình viết về data science, software, productivity, và linux. Khám phá ở dưới nha!"
  bio = "Hi! I'm lelouvincx. I'm writing about data science, dev life, productivity, linux... Let's discover!"
  links = [
    { email = "mailto:dinhminhchinh3357@duck.com" },
    { linkedin = "https://linkedin.com/in/lelouvincx" },
    { github = "https://github.com/lelouvincx" },
    { gitlab = "https://gitlab.com/lelouvincx" },
    { stack-overflow = "https://stackoverflow.com/users/10793419/lelouvincx" },
  #   { dev = "https://dev.to/username" },
  #   { discord = "https://discord.gg/invitecode" },
  #   { facebook = "https://facebook.com/username" },
  #   { hashnode = "https://username.hashnode.dev" },
  #   { medium = "https://medium.com/username" },
  #   { patreon = "https://www.patreon.com/username" },
  #   { steam = "https://steamcommunity.com/profiles/userid" },
  #   { telegram = "https://t.me/username" },
  #   { twitter = "https://twitter.com/username" },
  #   { youtube = "https://youtube.com/username" },
  ]
