languageCode = "en"
languageName = "English"
weight = 1
title = "lelouvincx's blog"

[params]
displayName = "EN"
isoCode = "en"
rtl = false
dateFormat = "2006-01-02"
# logo = "img/avatar.png"
description = "lelouvincx's website"
copyright = "© 2025 lelouvincx"

[params.author]
name = "lelouvincx"
email = "dinhminhchinh3357@gmail.com"
image = "img/avatar.png"
headline = "Mình viết về data engineering, software, productivity, và linux. Cùng khám phá ở dưới nhé!"
bio = "Hi! I'm lelouvincx. I'm writing about data engineering, dev life, productivity, and linux... Let's discover!"
links = [
  { linkedin = "https://linkedin.com/in/lelouvincx" },
  { github = "https://github.com/lelouvincx" },
  { email = "mailto:dinhminhchinh3357@gmail.com" },
  # { goodreads = "https://www.goodreads.com/user/show/73433536-lelouvincx" },
  # { stack-overflow = "https://stackoverflow.com/users/10793419/lelouvincx" },
  # { gitlab = "https://gitlab.com/lelouvincx" },
  # { dev = "https://dev.to/username" },
  # { discord = "https://discord.gg/invitecode" },
  # { facebook = "https://facebook.com/username" },
  # { hashnode = "https://username.hashnode.dev" },
  # { medium = "https://medium.com/username" },
  # { patreon = "https://www.patreon.com/username" },
  # { steam = "https://steamcommunity.com/profiles/userid" },
  # { telegram = "https://t.me/username" },
  # { twitter = "https://twitter.com/username" },
  # { youtube = "https://youtube.com/username" },
]
